In [5]:
import numpy as np
np.__version__


'2.0.1'

In [6]:
arr=np.array([10,20,30,40,50,569])        # homogeneous array
arr

array([ 10,  20,  30,  40,  50, 569])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim

1

In [9]:
arr.size      

6

In [10]:
len(arr)

6

In [11]:
arr.dtype

dtype('int64')

In [12]:
arr1=np.array([10.10,10,20,200,"ram"])         # all items become string by adding a string
arr1

array(['10.1', '10', '20', '200', 'ram'], dtype='<U32')

In [13]:
arr2=np.array([10.10,20,30,40,50.6])    # on float value ki bjh se all item become float so hume same datatype item rkhne h 
arr2
arr2.dtype

dtype('float64')

In [14]:
arr        #all item are in index position 

array([ 10,  20,  30,  40,  50, 569])

In [15]:
arr[2]

np.int64(30)

In [16]:
arr[:--4]

array([10, 20, 30, 40])

In [17]:
arr[-1:-4]

array([], dtype=int64)

In [18]:
arr[3:]

array([ 40,  50, 569])

In [19]:
arr[4:]

array([ 50, 569])

In [20]:
arr[-1:-4:-1]

array([569,  50,  40])

In [21]:
arr[-3:7]

array([ 40,  50, 569])

In [22]:
arr+10

array([ 20,  30,  40,  50,  60, 579])

In [23]:
arr*5

array([  50,  100,  150,  200,  250, 2845])

In [24]:
arr/5


array([  2. ,   4. ,   6. ,   8. ,  10. , 113.8])

In [25]:
a=min(arr)
b=max(arr)
c=sum(arr)
d=np.mean(arr)
e=np.median(arr)  
print(a)
print(b)
print(c)
print(d)
print(e)


10
569
719
119.83333333333333
35.0


In [26]:

np.random.randint(1,9)

6

In [27]:
import random    # isme sirf do he values hoto h 
random.randint(1,100)

34

  ------------------------    ASSIGNEMENT QUIZ ON ARRAY -----------------

In [28]:
arr5=np.random.randint(1,450,500)     # isme do se jada value bho h skti h or occirence of number bhi hota h 
arr5       # try to calculate no. of item that are less than 100
# try to calculate no. of even number 
# find mode of this arr5

array([113, 283, 148, 401, 107, 303, 130,  82, 331,  95, 319, 341, 157,
        53, 108, 370, 351, 317, 353, 111,  74, 144, 339, 108, 449,  24,
       217, 243, 154,  12,  24, 284,  33, 253, 238, 101, 189, 226,  69,
       145, 298, 269, 348, 181, 127,  35, 378, 123, 303, 418, 337, 275,
       248, 305, 193,  54, 133, 414,  90, 126, 433, 136,  96,  44, 443,
        81, 140, 274, 126, 411, 159, 133, 265, 172, 301, 213, 145, 208,
       349, 185, 204, 107, 368, 382,  31, 428,  97, 113, 379,  78,  44,
       278, 235, 134, 406, 436, 230, 401, 238, 356,  99, 121, 367, 404,
       213, 364, 133,  14, 373, 376, 444, 110,  78, 341, 213,  93, 131,
       293, 352,  83, 211, 187,  48, 116, 249,  40, 286, 358, 289, 422,
       314,   6, 195, 159, 319, 355, 228, 174,  61, 154, 276, 250,  22,
       266, 127,  97,  35, 385,  93, 140, 140,  99, 404,  30, 162, 290,
       267, 341, 143, 344, 182, 269, 280, 300, 145, 249, 303, 207, 414,
       275, 419, 279, 334, 146,  60, 380, 164,  92, 387, 164,  2

In [29]:
print(arr5.size)



500


In [30]:
'''for even_no in arr5:
    if even_no%2==0:
        print(even_no)'''
        


'for even_no in arr5:\n    if even_no%2==0:\n        print(even_no)'

In [31]:
 
'''for lessthan_100 in arr5:
    if lessthan_100<100:
        print(lessthan_100)
        lessthan_100+=1
'''

        

'for lessthan_100 in arr5:\n    if lessthan_100<100:\n        print(lessthan_100)\n        lessthan_100+=1\n'

In [32]:
num_even1=np.sum(arr5%2==0)
num_even1

np.int64(234)

In [33]:
num_even2=np.count_nonzero(arr5%2==0)
num_even2

234

In [34]:
mask=(arr5%2==0)
num_even3=arr5[mask]
result_size=num_even3.size
print("Even number are : ",num_even3)
print("Size of even numbers in aar5 :",result_size)

Even number are :  [148 130  82 108 370  74 144 108  24 154  12  24 284 238 226 298 348 378
 418 248  54 414  90 126 136  96  44 140 274 126 172 208 204 368 382 428
  78  44 278 134 406 436 230 238 356 404 364  14 376 444 110  78 352  48
 116  40 286 358 422 314   6 228 174 154 276 250  22 266 140 140 404  30
 162 290 344 182 280 300 414 334 146  60 380 164  92 164  28  44 242 246
  52 400 346 314 272 158 418  58 442 194  18 384 218 110  40 216 352 284
  42  28 132 144 112  74 128  66 234 326 182 248 246  18 426 190 360 166
 190 172 144 434  20 364 226 388 130 334 418 400 382 324  22  70  48 294
 364 234  68 446  22  34 114 228 424 380 118 342  90 436 180 234  90 304
 258 390 346  98 398 334 356 448  74 332 332 396 338 254 286 412 252 268
 438  92  78 252 226 280   8  86 432 236  70  64 444 116 274  36  40  78
 446 138 140 340 248  84 386  66 310 296 294 346 136 148 118 276 348 420
 174 308 346 334 212 118 392  32 144 398 196 394 118   6 298 160 376 206]
Size of even numbers in aar5 : 

In [35]:
num_lessthan_100_1=np.sum(arr5<100)
num_lessthan_100_1

np.int64(116)

In [36]:
num_lessthan_100_2=np.count_nonzero(arr5<100)
num_lessthan_100_2

116

In [37]:
mask=(arr5<100)
num_lessthan_100_3=arr5[mask]
less_100_size=num_lessthan_100_3.size
print("LESS THAN 100 NUMBERS ARE AS FOLLOWS :",num_lessthan_100_3)
print("THE SIZE OF LESS THAN 100 NUMBER IN arr5 ARE AS FOLLOWS :",less_100_size)

LESS THAN 100 NUMBERS ARE AS FOLLOWS : [82 95 53 74 24 12 24 33 69 35 54 90 96 44 81 31 97 78 44 99 14 78 93 83
 48 40  6 61 22 97 35 93 99 30 60 92 28 44 52 85 67 58 65 93 18 47 40 42
 28  5 74 66 43 11 18 47 69 45 20 51 45 22 70 48 43 41 19 68 22 34 95 90
 13 90 35 49 59 81 85 21 93 98  7 74 75 51 51 83 92 78 79  8 86 70 63 64
  7 36 40 31 78 49 84 66 77  1  1 45  3 77 17 32 31 71  6 63]
THE SIZE OF LESS THAN 100 NUMBER IN arr5 ARE AS FOLLOWS : 116


In [38]:
print()

In [39]:
import statistics as st
import numpy as np 

In [47]:
mode=st.mode(arr5)
print(mode)


303


In [41]:
import random,string

In [42]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [43]:
string.digits

'0123456789'

In [44]:
alpha=string.ascii_letters+string.digits+string.punctuation
alpha

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [45]:
random.choice(alpha)

'('

In [46]:
string.printable

'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'