multidimensional array:
accessing:
1d=[itemindex]
2d=[row,column]
3d=[table.row.column]
ravel,flatten,reshape(size likhna h ) function used to convert nd to 1d

In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,450,500)
arr

array([ 46, 304, 342, 353, 173, 392, 331,  44, 268, 439, 203, 180,  14,
       189, 445, 364, 377,  84, 192,  35,  18, 316,  55, 257, 310,  23,
        80, 391, 303,   8, 118, 443, 237, 155,  42, 157, 325, 207, 108,
       201, 319, 437, 437, 275, 179,  50, 318, 222, 310, 143, 219,  17,
       399, 203, 409, 354,  53,  73, 367, 310, 257,  65, 276,  82, 293,
       216, 386, 151, 367,  99, 175, 250, 260,  60, 385, 344, 162, 303,
       288, 101, 263, 234, 221, 310,  65, 110, 287,  97, 190, 387, 194,
       425,  52, 275,   5, 360,  13, 392, 116, 294, 403, 253, 167, 412,
       358, 288, 371, 444, 288,  78, 183, 345, 448, 359, 209,  81, 177,
        80, 282, 153, 398, 279, 344, 364, 435, 106, 349, 152, 390, 369,
       159,  31, 150,  40, 278, 113, 302, 100, 274, 128,  69, 275, 182,
        10, 396,  50, 167, 185, 244, 221, 242, 252,   4, 104, 410,  86,
       210, 403,  94, 382,  13, 391, 449, 379, 245, 214, 120, 107, 391,
        73, 352, 371, 444, 420, 144, 414,  92, 441, 387, 322, 19

In [4]:
arr<100

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False,  True,  True, False,  True, False, False,  True,  True,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False,  True,  True, False, False, False,  True, False,
        True, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False,  True, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False,

In [5]:
sum(arr<100)

np.int64(107)

In [6]:
arr[arr<100]

array([46, 44, 14, 84, 35, 18, 55, 23, 80,  8, 42, 50, 17, 53, 73, 65, 82,
       99, 60, 65, 97, 52,  5, 13, 78, 81, 80, 31, 40, 69, 10, 50,  4, 86,
       94, 13, 73, 92, 50, 21, 87, 26, 82, 18, 48, 46, 80, 43, 46, 46, 97,
       46, 14, 71, 23, 79, 26,  6, 75, 30, 85, 11, 18, 72, 89, 78, 54, 43,
       81,  1, 99, 22, 58, 19, 70, 68, 12, 36, 98, 14, 77, 34, 99, 52,  2,
       36, 48, 52, 82, 31, 96, 39, 50, 85, 92, 94, 54, 49, 47, 89,  9,  1,
       21, 36, 48, 27, 41], dtype=int32)

In [7]:
len(arr[arr<100])

107

In [8]:
ls=[[1,2,3],[4,5,6],[7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr2d=np.array(ls,dtype="float")
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
arr2d.ndim

2

In [11]:
arr2d.shape  # shape apko rows and columns ke bare m batata h 

(3, 3)

In [12]:
arr2d[0]

array([1., 2., 3.])

In [13]:
arr2d[0:3]

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [14]:
arr2d[-1]

array([7., 8., 9.])

In [15]:
arr2d[-3:-1]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
arr2d[1:3,1:3]

array([[5., 6.],
       [8., 9.]])

In [17]:
arr2d[0:3,0:2]

array([[1., 2.],
       [4., 5.],
       [7., 8.]])

In [18]:
arr2d[0:2,1:3]

array([[2., 3.],
       [5., 6.]])

In [19]:
arr2d[1:,0:2]

array([[4., 5.],
       [7., 8.]])

In [20]:
arr2d[-2:][-3:]

array([[4., 5., 6.],
       [7., 8., 9.]])

In [21]:
arr2d[1,1]

np.float64(5.0)

In [22]:
arr2d[:,1:]


array([[2., 3.],
       [5., 6.],
       [8., 9.]])

In [23]:
arr1=np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
arr2=np.ones(5)
arr2

array([1., 1., 1., 1., 1.])

In [25]:
arr3=np.linspace(1,50,20)
arr3

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [26]:
ls3d=[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
ls3d

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [27]:
# 3d array
arr3d=np.array(ls3d)
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [28]:
arr3d.ndim

3

In [29]:
arr3d.shape  # 4 means table 3 rows 3 column

(4, 3, 3)

In [30]:
arr3d[0:3]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [31]:
arr3d[0:,0,0:]


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [32]:
arr3d[-4:,-3,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [33]:
arr3d[2,1:,1:]

array([[5, 6],
       [8, 9]])

In [34]:
arr3d[0,1:,1:]

array([[5, 6],
       [8, 9]])

In [35]:
arr3d[-4,-2:,-2:]

array([[5, 6],
       [8, 9]])

In [36]:
arr3d[0:,1:,1:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [37]:
arr3d[0,1,1]

np.int64(5)

In [38]:
arr3d[:,2:,::-1]

array([[[9, 8, 7]],

       [[9, 8, 7]],

       [[9, 8, 7]],

       [[9, 8, 7]]])

In [39]:
arr3d.ravel()        # ravel used to convert n dimension to 1 d

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr3d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr3d.reshape(36)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

--------------ASSIGNEMENT QUESTION ---------------------------
1. argmin()  , argmax()  ,argsort() ,  

In [43]:
x=np.array([1,2,1,3,4,5,10,9,5,6,8,7])
min=np.argmin(x) 
print(min)


0


In [44]:
max=np.argmax(x)
print(max)

6


In [45]:
sort=np.argsort(x)
print(sort)

[ 0  2  1  3  4  5  8  9 11 10  7  6]
