MATRIX IN NUMPY:  

MATRIX AND ARRAY M DIFFERENCER M UNKE MULTIPLY KE BASISI PR KR SKTE H . IN MATRIX WE USE DOT () FUNCTION FOR PRODUCT OF TWO MATRIX.

In [1]:
import numpy as np

In [4]:
mat=np.matrix([[1,2],[1,2]])
print(mat)
print()
print(type(mat))

[[1 2]
 [1 2]]

<class 'numpy.matrix'>


In [5]:
arr=np.array([[1,2],[1,2]])
print(arr)
print()
print(type(arr))           

[[1 2]
 [1 2]]

<class 'numpy.ndarray'>


In [6]:
mat1=np.matrix([[7,2],[1,4]])
mat2=np.matrix([[6,2],[1,8]])
print(mat1)
print(mat2)

[[7 2]
 [1 4]]
[[6 2]
 [1 8]]


In [20]:
# operations on matrix 
add=np.add(mat1,mat2)
print(add)
print()
s=np.subtract(mat1,mat2)
print(s)
print()
product=np.dot(mat1,mat2)    # difference between matrix and array see here
print(product)

[[13  4]
 [ 2 12]]

[[ 1  0]
 [ 0 -4]]

[[44 30]
 [10 34]]


In [12]:
# operations on array
arr1=np.array([[7,2],[1,4]])
arr2=np.array([[6,2],[1,8]])
print(arr1)
print(arr2)

[[7 2]
 [1 4]]
[[6 2]
 [1 8]]


In [23]:
# operations on array
a=np.add(arr1,arr2)
print(a)
print()
s1=np.subtract(arr1,arr2)
print(s1)
print()
product1=np.multiply(arr1,arr2)           # difference between matrix and array see here
print(product1)

[[13  4]
 [ 2 12]]

[[ 1  0]
 [ 0 -4]]

[[42  4]
 [ 1 32]]
