ITERATING NUMPY ARRAYS: alg krke loop ki help se access krna


In [2]:
import numpy as np

In [3]:
x=[1,2,3,4,5,6,7]
for i in x:
    print(i)

1
2
3
4
5
6
7


In [4]:
arr= np.array([9,8,6,5,4])
print(arr)           # iteration in 1d
print()
for i in arr:
    print(i)

[9 8 6 5 4]

9
8
6
5
4


In [6]:
# iteration in 2d 
arr1=np.array([1,2,3,4,5,6,7,8,9,12])
reshape=arr1.reshape(2,5)
print(reshape)
print()
for i in reshape:
    for j in i:
        print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 12]]
1
2
3
4
5
6
7
8
9
12


In [7]:
# iteration in 3d
arr2=np.array([1,2,3,4,5,6,7,8,9,12,13,14])
a3d=arr2.reshape(3,2,2)
print(a3d)
print()
for i in a3d:
    for j in i:
        for k in j:
            print(k)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 12]
  [13 14]]]

1
2
3
4
5
6
7
8
9
12
13
14


In [11]:
# iteration through nditer function :
print(a3d)
print()

for i in np.nditer(a3d):
    print(i)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 12]
  [13 14]]]

1
2
3
4
5
6
7
8
9
12
13
14


In [12]:
# change datatype of existing array using flag and dtype
print(a3d)
print()

for i in np.nditer(a3d , flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 12]
  [13 14]]]

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'12')
np.bytes_(b'13')
np.bytes_(b'14')


In [13]:
# ITERATION WITH ndenumerate() it gives indexing along with value
print(a3d)
print()

for i in np.ndenumerate(a3d):
    print(i)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 12]
  [13 14]]]

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 1, 0), np.int64(3))
((0, 1, 1), np.int64(4))
((1, 0, 0), np.int64(5))
((1, 0, 1), np.int64(6))
((1, 1, 0), np.int64(7))
((1, 1, 1), np.int64(8))
((2, 0, 0), np.int64(9))
((2, 0, 1), np.int64(12))
((2, 1, 0), np.int64(13))
((2, 1, 1), np.int64(14))
