list vs array in python 
array :
consume less memmory and faster and convinient to use than list.
more function present 


import numpy 

In [1]:
import numpy as np

ways to create array :

In [5]:
x=[10,20,30,40]
y=np.array(x)
y

z=np.array([10,20,30,40,40])
z

array([10, 20, 30, 40, 40])

In [12]:
l=[]
for i in range(1,5):
    item=eval(input(("enter the item :")))
    l.append(item)
print(l)
arr=np.array(l)
arr   

[10, 20, 30, 40]


array([10, 20, 30, 40])

types of array : 1d,3d,2d,nd

In [13]:
arr1=np.array([[1,2,3],[1,2,3]])      # 2d array 
arr1

array([[1, 2, 3],
       [1, 2, 3]])

In [14]:
arr1.ndim     # check the dimension of array


2

In [15]:
arr_n=np.array([1,2,3,4,5,6],ndmin=10)     # make n dimesion array 
arr_n

array([[[[[[[[[[1, 2, 3, 4, 5, 6]]]]]]]]]])