MATRIX FUNCTION IN NUMPY:

In [1]:
import numpy as np

In [3]:
mat=np.matrix([[1,2,3],[2,4,5]])
print(mat)

[[1 2 3]
 [2 4 5]]


In [7]:
# transpose of matrix
t=np.transpose(mat)
print(t)
print()
# shorthand of transpose
t1=mat.T
print(t1)

[[1 2]
 [2 4]
 [3 5]]

[[1 2]
 [2 4]
 [3 5]]


In [10]:
# swapaxes same as transpose
swap=np.swapaxes(mat,0,1)
print(swap)

[[1 2]
 [2 4]
 [3 5]]


In [18]:
mat1=np.matrix([[1,2],[4,5]])
print(mat1)
print()
s=np.swapaxes(mat1,0,1)
print(s)

[[1 2]
 [4 5]]

[[1 4]
 [2 5]]


In [19]:
# inverse matrix
inverse=np.linalg.inv(mat1)
print(inverse)

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [20]:
# power of matrix
power=np.linalg.matrix_power(mat1,0)
print(power)

[[1 0]
 [0 1]]


In [21]:
power2=np.linalg.matrix_power(mat1,3)
print(power2)

[[ 57  78]
 [156 213]]


In [22]:
power3=np.linalg.matrix_power(mat1,-3)
print(power3)

[[-7.88888889  2.88888889]
 [ 5.77777778 -2.11111111]]


In [26]:
# derminate of matrix
mat2=np.matrix([1,2,3,4,5,6,7,8,9])
reshape=np.reshape(mat2,(3,3))
print(reshape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
derminant=np.linalg.det(reshape)
print(derminant)

0.0
