INSERT , APPEND AND DELETE FUNCTION IN NUMPY ARRAY:

In [11]:
import numpy as np

In [12]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.dtype)

[1 2 3 4 5]
int64


In [13]:
# insert function data insert krta h according to existing array datatype .
# insert () used to inset value have 3 parameter 1.variable name,position of value ,add value name ,isme data integer he insert hota h not float.
i=np.insert(arr1,2,100)
i

array([  1,   2, 100,   3,   4,   5])

In [14]:
arr2=np.array([1.2,3.4,5.6,7.8,8.9])
print(arr2)
print()
i2=np.insert(arr2,3,100)  # data insert acc.to arr2 datatype
print(i2)

[1.2 3.4 5.6 7.8 8.9]

[  1.2   3.4   5.6 100.    7.8   8.9]


In [29]:
# append () used to insert data at end position and insert any datatype in existing array 
arr3=np.array([['a','b'],['c','d']])
print(arr3)
print()
a=np.append(arr3,[[1,2]],axis=0)
print(a)

[['a' 'b']
 ['c' 'd']]

[['a' 'b']
 ['c' 'd']
 ['1' '2']]


In [20]:
# delete used to delete item from array 
arr5=np.array([1,2,3,400,5,6,7])
print(arr5)
print()
d=np.delete(arr5,3)
print(d)

[  1   2   3 400   5   6   7]

[1 2 3 5 6 7]


In [25]:
arr6=np.array([[1,2,3],[400,5,6],[7,8,9]])
print(arr6)
print()
d1=np.delete(arr6,1,axis=0)
print(d1)

[[  1   2   3]
 [400   5   6]
 [  7   8   9]]

[[1 2 3]
 [7 8 9]]
