datatype in numpy

In [1]:
import numpy as np

In [2]:
int_arr=np.array([1,2,3,4,5])
print(int_arr.dtype)

int64


In [3]:
float_arr=np.array([10,20.2,30.3,40.4])
print(float_arr.dtype)

float64


In [4]:
string_arr=np.array(["a","b",'c','d',1,1.1])
print(string_arr.dtype)

<U32


conversion of datatype  : three ways 
1. directly dtype = int in array inside.
2. as a function like np.float(arr)
3. by using  arr.astype(float)

In [6]:
arr=np.array([1,2,3,4,5],ndmin=4 , dtype=float)
print(arr,arr.dtype)

[[[[1. 2. 3. 4. 5.]]]] float64


In [12]:
arr1= np.array([[1,2,3,4,5,6,7]])
convert_arr=np.float16(arr1)
print(arr1,arr1.dtype)
print(convert_arr,convert_arr.dtype)

[[1 2 3 4 5 6 7]] int64
[[1. 2. 3. 4. 5. 6. 7.]] float16


In [14]:
arr2=np.array(['a','b','c','d'])
new=arr2.astype(float)
print(arr2,arr2.dtype)


NameError: name 'float_' is not defined