JOIN AND SPLIT NUMPY ARRAY:
1. for join two array we use concatenate () and stack ()function.
a.. concatenate function m app axis bhi de skte h  like np.concatenate((a,b),axis=0).
b.. stack m 3 hote h   1.np.vstack = column m join krna.
2. hstack= row m join krna .
3. dstack= height ke along join krna 

............ split()= used to break 1 array in multiple array.
1. split () apka array function h like np.array_split(a,3,axis=0)
2. split hone ke bad array list m convert ho jata h .

In [1]:
import numpy as np

In [6]:
arr1=np.array([1,2,3,4,5])       # in 1 d
arr2=np.array([4,5,6,7,8])
con_arr=np.concatenate((arr1,arr2),axis=0)
con_arr

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [7]:
x= np.array([[1,2,3],[4,5,6]])
y= np .array([[6,5,4],[8,1,2]])
print(x)
print()         # axis=1 means x axis
print(y)
print()
join=np.concatenate((x,y),axis=1)
print(join)


[[1 2 3]
 [4 5 6]]

[[6 5 4]
 [8 1 2]]

[[1 2 3 6 5 4]
 [4 5 6 8 1 2]]


In [8]:
x= np.array([[1,2,3],[4,5,6]])
y= np .array([[6,5,4],[8,1,2]])
print(x)
print()
print(y)         # axis = 0 means y axis
print()
join=np.concatenate((x,y),axis=0)
print(join)

[[1 2 3]
 [4 5 6]]

[[6 5 4]
 [8 1 2]]

[[1 2 3]
 [4 5 6]
 [6 5 4]
 [8 1 2]]


In [15]:
# stack ()
a=np.array([[10,20,30],[40,50,60]])
b= np.array([[1,4,5],[6,2,3]])
join1=np.stack((a,b),axis=1)
print( "stack : ",join1)
print()
row=np.hstack((a,b))
print( "hstack : ",row)
print()
column=np.vstack((a,b))
print("vstack : ",column)
print()
height=np.dstack((a,b))
print("dstack : ",height)

stack :  [[[10 20 30]
  [ 1  4  5]]

 [[40 50 60]
  [ 6  2  3]]]

hstack :  [[10 20 30  1  4  5]
 [40 50 60  6  2  3]]

vstack :  [[10 20 30]
 [40 50 60]
 [ 1  4  5]
 [ 6  2  3]]

dstack :  [[[10  1]
  [20  4]
  [30  5]]

 [[40  6]
  [50  2]
  [60  3]]]


SPLIT


In [22]:
a=np.array([1,2,3,4,5,6])
split_array=np.array_split(a,4,axis=0)
print(split_array)   # same for 2d array
print()
print("datatype of 4 split arrays:", type(split_array))
print()
print(split_array[1])

[array([1, 2]), array([3, 4]), array([5]), array([6])]

datatype of 4 split arrays: <class 'list'>

[3 4]


In [30]:
a=np.array([[1,2],[3,4],[5,6]])
split_array=np.array_split(a,3 ,axis=1)
print(split_array)  
print()
print("datatype of 4 split arrays:", type(split_array))
print()
print(split_array[1])

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]

datatype of 4 split arrays: <class 'list'>

[[2]
 [4]
 [6]]
