BROADCASTING IN NUMPY:
jb same dimension na ho do array ki to unme aritmetic operation perform nhi hote h to is prblm ke liye broadcasting use krte h .


In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6,7,8,9,12])
arr2=np.array([1,2,3,4,5,6,7,8])
add= arr1+arr2
add

ValueError: operands could not be broadcast together with shapes (10,) (8,) 

In [4]:
reshape=arr1.reshape(1,10)
reshape

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12]])

In [5]:
reshape1=arr2.reshape(1,8)
reshape1

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [6]:
add1=reshape+reshape1
add1

ValueError: operands could not be broadcast together with shapes (1,10) (1,8) 

In [9]:
arr3=np.array([1,2,3])
arr4=np.array([[1],[2],[3]])
print(arr3)
print()              # here broadcasting perform.
print(arr4)
add3=arr3+arr4
print()
print(add3)

[1 2 3]

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]
