NUMPY ARRAY FUNCTION : SEARCH , SEARCHEDSORT ,SORT , FILTER 

In [1]:
import numpy as np

In [5]:
# search in this where () is used to search item
arr=np.random.randint(1,450,10)
arr

array([ 60,  21, 160, 285, 127,  98, 198, 425, 348, 314], dtype=int32)

In [6]:
greater_100=np.where(arr>100) # where function return the index of search number
greater_100

(array([2, 3, 4, 6, 7, 8, 9]),)

In [ ]:
# searchedsort: it is used to place value in array and also side mention and return value placed index 

In [11]:
arr1=np.array([1,2,3,4,5])
a=np.searchsorted(arr1,['a','b','c'])
print(a)
print(a)
print(arr1)

[5 5 5]
[1 2 3 4 5]


In [13]:
# sort() used to arrange value in increasing order.
x=np.array([[10,2],[6,1],[30,9]])
print(x)
print()
y=np.sort(x)
print(y)

[[10  2]
 [ 6  1]
 [30  9]]

[[ 2 10]
 [ 1  6]
 [ 9 30]]


In [17]:

# filter is used to make a new array of chosen item. we have to give true and false to choose the item in f.
ab=np.array(['a','b','c','d','e'])
print(ab)
print()
f=[True,False,True,False,False]
fiter_arr=ab[f]
print( "your filter array is  :",fiter_arr)




['a' 'b' 'c' 'd' 'e']

your filter array is  : ['a' 'c']
