how to generate random array

In [8]:
import numpy as np

1. rand()  isme sare numbers 0 to 1 ke bich m hote h 
all positive numbers

In [9]:
random_arr1=np.random.rand(5)
random_arr1

array([0.77552883, 0.04297479, 0.99493919, 0.10364331, 0.96980201])

2. randn() isme number closest to 0 hota h and negative and positive dono number hota h 

In [10]:
random_arr2=np.random.randn(8)
random_arr2

array([ 0.12287475, -0.84872509, -1.31785516,  0.9918931 ,  1.37225626,
       -0.34637066,  1.25268266,  0.49505727])

3.ranf()  isme value float krti h and 1 include nhi hota h 

In [11]:
random_arr3=np.random.ranf(8)
random_arr3

array([0.61938178, 0.32633099, 0.04150444, 0.57014361, 0.25210816,
       0.59349687, 0.85740778, 0.44544413])

4. randint()   isme min ,max,total length three values insert hoti h 

In [12]:
random_arr4=np.random.randint(2,10,10)
random_arr4

array([8, 4, 9, 3, 2, 7, 7, 3, 3, 9], dtype=int32)