COPY VS VIEW () IN NUMPY:
1.copy apka old array ka 1 new copy alg location pr bna deta h .
2.view apka old array ko dikhata h not made a new copy on another location.
3.if we change  old array then new copy array doesn,t change.
4.but view  new array change .


In [1]:
import numpy as np


In [11]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print()
arr_copy=arr.copy()
print( "copy array:" , arr_copy)

[1 2 3 4 5 6]

copy array: [1 2 3 4 5 6]


In [12]:
# if we change the arr then show what changes occured means if we change arr then arr_copy not change .
arr[4]=59
print(arr)
print()
print("arr_copy:", arr_copy)

[ 1  2  3  4 59  6]
arr_copy: [1 2 3 4 5 6]


In [14]:
# view ()
arr1=np.array([76,89,56,45,30])
print(arr1)
print()
arr1_view=arr1.view()
print("view array:", arr1_view)



[76 89 56 45 30]

view array: [76 89 56 45 30]


In [15]:
arr1[3]=00   # view m agr arr1 change hua h to arr1_view bhi change hoga.
print(arr1)
print()
arr1_view=arr1.view()
print("view array:", arr1_view)


[76 89 56  0 30]

view array: [76 89 56  0 30]
