numpy arithmetic function:

In [1]:
import numpy as np

In [7]:
arr=np.array([10,20,30,40,59])
min=np.min(arr)
max=np.max(arr)
argmin=np.argmin(arr)
argmax=np.argmax(arr)
sqrt=np.sqrt(arr)
cumsum=np.cumsum(arr)
sin=np.sin(arr)
cos=np.cos(arr)
print(min)
print(max)
print(sin)
print(cos)
print(cumsum)
print(argmin)
print(argmax)
print(sqrt)


10
59
[-0.54402111  0.91294525 -0.98803162  0.74511316  0.63673801]
[-0.83907153  0.40808206  0.15425145 -0.66693806 -0.77108022]
[ 10  30  60 100 159]
0
4
[3.16227766 4.47213595 5.47722558 6.32455532 7.68114575]


In [6]:
arr2d=np.array([[1,2,3,4],[10,1,30,2]])
min_yaxis=np.min(arr2d,0)
min_xaxis=np.min(arr2d,1)
print(min_yaxis)
print(min_yaxis)


[1 1 3 2]
[1 1 3 2]
