special numpy array 

In [32]:
import numpy as np


In [33]:
arr_0=np.zeros(4)
print(arr_0)

arr1_0=np.zeros((3,4))
print(arr1_0)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
arr_1=np.ones(3)
arr_1

array([1., 1., 1.])

empty array m pichli wali values aa jati h 

In [35]:
arr_empty=np.empty(5)
arr_empty

array([ 2.,  4.,  6.,  8., 10.])

In [36]:
arr_range=np.arange(2,8,2)
arr_range

array([2, 4, 6])

In [37]:
arr_diagonal=np.eye(4,4)
arr_diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
arr_spaceinterval=np.linspace(2,10,num=4)
arr_spaceinterval

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])