numpy array shape and reshape :
shape btata h array m kitni rows or kitne column h 
reshape values ko given nd array m change krta h 

In [8]:
import numpy as np

In [9]:
arr1d=np.array([1,2,3,4,5,6,8,9,7])
arr1d

array([1, 2, 3, 4, 5, 6, 8, 9, 7])

In [14]:
arr1d.shape


(9,)

In [15]:
arr1d.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

In [16]:
arr1d.reshape(2,2,2)

ValueError: cannot reshape array of size 9 into shape (2,2,2)

In [18]:
arrnd=np.array([1,2,3,4,5,6,7,8,9,8,7,6,5,4,3,2,1,3], ndmin=5)
arrnd

array([[[[[1, 2, 3, 4, 5, 6, 7, 8, 9, 8, 7, 6, 5, 4, 3, 2, 1, 3]]]]])

In [19]:
arrnd.shape

(1, 1, 1, 1, 18)

In [23]:
arr=arrnd.reshape(2,3,3)
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[8, 7, 6],
        [5, 4, 3],
        [2, 1, 3]]])

In [24]:
arr.shape

(2, 3, 3)

In [25]:
arrnd.reshape(1,3,3,2)

array([[[[1, 2],
         [3, 4],
         [5, 6]],

        [[7, 8],
         [9, 8],
         [7, 6]],

        [[5, 4],
         [3, 2],
         [1, 3]]]])