NUMPY ARRAY PART 2  :  SHUFFLE,UNIQUE,RESIZE,FLATTEN,RAVEL


In [2]:
import numpy as np

In [3]:
# shuffle is random function used to shuffle value like np.random.shuffle
a=np.array([1,2,3,4,5,6])
np.random.shuffle(a)
print(a)

[2 3 6 1 4 5]


In [4]:
# unique is used to find the unique value
x=np.array([1,1,2,2,3,3,4,4,5])
y=np.unique(x)
y

array([1, 2, 3, 4, 5])

In [5]:
# resize () ye array ki dimension change krta h 
b=np.array([1,1,2,2,3,3,4,4,5])
ab=np.resize(b,(1,3,3))
print(ab)

[[[1 1 2]
  [2 3 3]
  [4 4 5]]]


In [9]:
arr1= np.array([[[1,2,3],[4,5,6]],[[7,8,9] ,[1,2,3]],[[4,5,6],[7,8,9]]])
print(arr1)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[4 5 6]
  [7 8 9]]]


In [18]:
# flatten () apka nd ko 1d m convert krta h by giving order a k c f 
flatten=arr1.flatten(order='K')
flatten

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# ravel bhi apka nd array ko 1d m  convert krta h 
arr2= np.array([[[1,2,3],[4,5,6]],[[7,8,9] ,[1,2,3]],[[4,5,6],[7,8,9]]])
print(arr2)
print()
ravel=arr2.ravel(order='A')
print(ravel)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[4 5 6]
  [7 8 9]]]

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
