arithmetic operation in numpy

we can perform arithmetic operation in three ways:
1. directly add from arr1
2. make two array and directly add these two
3. use np.add,np.mod,np.divide 

In [1]:
import numpy as np

In [2]:
arr1=np.array([10,20,30,40,50])
add=arr1+3
sub=arr1-3
mod=arr1%3
divide=arr1/3
power=arr1**3
multiply=arr1*3
reciprocal=1/arr1
print(add)
print(sub)
print(mod)
print(divide)
print(power)
print(reciprocal)
print(multiply)

[13 23 33 43 53]
[ 7 17 27 37 47]
[1 2 0 1 2]
[ 3.33333333  6.66666667 10.         13.33333333 16.66666667]
[  1000   8000  27000  64000 125000]
[0.1        0.05       0.03333333 0.025      0.02      ]
[ 30  60  90 120 150]


In [17]:
arr2=np.array([[1,2,3,4],[6,7,8,9]] )
arr3=np.array([[10,20,30,40],[7,8,9,6]] )
new=arr2+arr3
print(new)

[[11 22 33 44]
 [13 15 17 15]]


In [6]:
new1=arr2-arr3
new2=arr2**arr3
new3=arr2%arr3
print(new1)
print(new2)
print(new3)


[[[ -9 -18 -27 -36]]]
[[[              1         1048576 205891132094649               0]]]
[[[1 2 3 4]]]


In [7]:
ary=np.array([1,2,3,4])
ary1=np.array([30,40,50,60])
power=np.power(ary,ary1)
print(power)

[                  1       1099511627776 6048575297968530377
                   0]


In [8]:
reciprocal=np.reciprocal(ary)
print(reciprocal)

[1 0 0 0]
